# Generated by Django 2.0.6 on 2018-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinat1', models.FloatField()),
                ('coordinat2', models.FloatField()),
                ('Full', models.IntegerField()),
            ],
        ),
    ]
