# Generated by Django 2.0.6 on 2018-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunker',
            name='coordinat1D',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bunker',
            name='coordinat2D',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bunker',
            name='coordinat1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bunker',
            name='coordinat2',
            field=models.IntegerField(),
        ),
    ]
